import { mockProducersResponse } from '@bb/common/fixtures/producers/mockProducersResponse';

describe('Given mock Producers functions', () => {
  describe('when mockProducersResponse is called', () => {
    it('it returns two producers', () => {
      const res = mockProducersResponse();
      expect(res.data.producers).toHaveLength(2);
    });

    it('it returns two unique producers', () => {
      const res = mockProducersResponse();
      expect(res).toEqual({
        data: {
          producers: [
            {
              id: res.data.producers[0]?.id, // uuid generated by the function
              heartbeatAt: res.data.producers[0]?.heartbeatAt, // timstamp generated by the function
            },
            {
              id: res.data.producers[1]?.id, // uuid generated by the function
              heartbeatAt: res.data.producers[1]?.heartbeatAt, // timstamp generated by the function
            },
          ],
        },
      });
    });
  });
});
